FROM apache/nifi:1.24.0 AS builder

WORKDIR /opt/nifi/nifi-current/lib/

RUN wget https://jdbc.postgresql.org/download/postgresql-42.7.1.jar

FROM apache/nifi:1.24.0

COPY --from=builder /opt/nifi/nifi-current/lib/postgresql-42.7.1.jar /opt/nifi/nifi-current/lib/

EXPOSE 8080

WORKDIR /opt/nifi/nifi-current

# Start NiFi
CMD ["bin/nifi.sh", "run"]
