version: '3'

services:
  s3:
    image: minio/minio:RELEASE.2023-12-13T23-28-55Z-cpuv1
    ports:
      - "9000:9000"
    env_file:
      - .env_s3
    volumes:
      - ./data_minio:/data
    command: server /data
    networks:
      - network

  nifi:
    build:
      context: .
      dockerfile: Dockerfile.nifi
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    networks:
      - network

  postgres:
    image: postgres:alpine3.18
    ports:
      - "5432:5432"
    env_file:
      - .env_postgres
    networks:
      - network
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d

networks:
  network:
